site_name: Notes
site_url: http://seluj01.github.io/notes/
site_description: personal notes about engineering
site_author: jules matz
repo_url: https://github.com/seluj01/notes#

theme: mkdocs

nav:
  - Algebra:
    - matrix inversion: Algebra/matrix_inversion.md
  - Stats/Estim:
    - Gaussian: StatsEstim/gaussian.md
  - Geometry:
    - Geometry2D:
      - Geometry2D circle-circle intersection: Geometry2D/circle_circle_intersection.md
  - Tools:
    - Mardown: Tools/markdown.md
    - MkDocs: Tools/mkdocs.md

markdown_extensions:
  - mdx_math # for math
  - attr_list # for images, used to pass html parameters like size
  - admonition # for blocks

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML

plugins:
- search
